---
services:
  - name: Coaching
    title: Respect that will steer you to excellence
    description: I will find talented people, conceptualize winning strategies, deliver digestible training, and fortify morale consistently.
  - name: Teaching
    title: Self-motivation and experience to get qualified
    description: I will cultivate your interest in education and development, grade your assignments, evaluate your progress, and plan educational activities.
  - name: Consulting
    title: Knowledge to provide advice within your field
    description: I will analyze situations and provide appropriate solutions thanks to sound research techniques to collect the necessary data.
  - name: Coding
    title: Bring to life the next big idea
    description: I will liaise with the development managers, write clean, scalable code, create testing protocols, fix bugs, and deploy programs.
  - name: Testing
    title: Improve the usability of your website or app
    description: I will debug code, correct errors, and troubleshoot any issues with software code by following a testing methodology.
  